# Generated by Django 3.1.3 on 2020-11-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_auto_20201121_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
            ],
        ),
    ]
